apiVersion: v1
kind: Namespace
metadata:
  name: kiamol-authn-sre
  labels:
    kiamol: ch17
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sre2
  namespace: kiamol-authn-sre
---
apiVersion: v1
kind: Secret
metadata:
  name: sre2-sa-token
  namespace: kiamol-authn-sre
  annotations:
    kubernetes.io/service-account.name: sre2
type: kubernetes.io/service-account-token