apiVersion: v1
kind: ServiceAccount
metadata:
  name: serverless-cli
  labels:
    kiamol: ch21
---
apiVersion: v1
kind: Pod
metadata:
  name: serverless-cli
  labels:
    kiamol: ch21
spec:
  serviceAccountName: serverless-cli
  containers:
    - name: serverless-cli
      image: kiamol/ch21-serverless-cli
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: serverless-cli
  labels:
    kiamol: ch21
subjects:
- kind: ServiceAccount
  name: serverless-cli
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin   # tsk
  apiGroup: rbac.authorization.k8s.io