apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    kiamol: ch10-lab
spec:
  ports:
    - port: {{ .Values.servicePort }}
      targetPort: 80
  selector:
    app: {{ .Release.Name }}
    environment: {{ .Values.environment | lower }}
  type: {{ .Values.serviceType }}