apiVersion: v1
kind: Service
metadata:
  name: vweb
  labels:
    kiamol: ch09-lab
spec:
  ports:
    - port: 8090
      targetPort: http
  selector:
    app: vweb
    version: v1
  type: LoadBalancer