apiVersion: apiextensions.k8s.io/v1  # minimum 1.16
kind: CustomResourceDefinition
metadata:
  name: timechecks.ch20.kiamol.net
  labels:
    kiamol: ch20
spec:
  group: ch20.kiamol.net
  scope: Namespaced
  names:
    plural: timechecks
    singular: timecheck
    kind: TimeCheck
    shortNames:
    - tc
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                environment:
                  type: string
                interval:
                  type: integer 
      additionalPrinterColumns:
        - name: Environment
          type: string
          description: Environment
          jsonPath: .spec.environment
        - name: Interval
          type: string
          description: Interval
          jsonPath: .spec.interval