apiVersion: apps/v1
kind: Deployment
metadata:
  name: vweb-v2
  labels:
    kiamol: ch09-lab
    app: vweb
spec:
  replicas: 4
  selector:
    matchLabels:
      app: vweb
      version: v2
  template:
    metadata:
      labels:
        app: vweb
        version: v2
    spec:
      containers:
        - name: web
          image: kiamol/ch09-vweb:v2
          ports:
            - name: http
              containerPort: 80

