apiVersion: apps/v1
kind: Deployment
metadata:
  name: numbers-api-proxy
  namespace: kiamol-ch13-test
spec:
  selector:
    matchLabels:
      app: numbers-api-proxy
  template:
    metadata:
      labels:
        app: numbers-api-proxy
      annotations:
        fluentbit.io/parser: nginx
    spec:
      containers:
        - image: nginx:1.17-alpine
          name: nginx
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: config
              mountPath: "/etc/nginx/"
              readOnly: true
            - name: cache-volume
              mountPath: /data/nginx/cache
      volumes:
        - name: config
          configMap:
            name: numbers-api-proxy-config
        - name: cache-volume
          emptyDir: {}
