service: todo-api

provider:
  name: kubeless
  runtime: nodejs12
  hostname: api.todo.kiamol.local

plugins:
  - serverless-kubeless

functions:
  todo-api:
    description: 'ToDo list - create item API'
    handler: server.handler
    events:
      - http:
          path: /todos