apiVersion: v1
kind: Service
metadata:
  name: todo-web
  labels:
    kiamol: ch16
spec:
  type: LoadBalancer
  ports:
    - port: 8019
      targetPort: 80
  selector:
    app: todo-web
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-web-config
  labels:
    kiamol: ch16
data:
  config.json: |-
    {
      "Database" : {
        "Provider" : "Sqlite"
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-web
  labels:
    kiamol: ch16
spec:
  selector:
    matchLabels:
      app: todo-web
  template:
    metadata:
      labels:
        app: todo-web
    spec:
      containers:
        - name: web
          image: kiamol/ch04-todo-list
          volumeMounts:
            - name: config
              mountPath: "/app/config"
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: todo-web-config
