apiVersion: v1
kind: Namespace
metadata:
  name: kiamol-ch11-uat
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep
  namespace: kiamol-ch11-uat
  labels:
    app: sleep
spec:
  selector:
    matchLabels:
      app: sleep
  template:
    metadata:
      labels:
        app: sleep
    spec:
      containers:
      - name: sleep
        image: kiamol/ch03-sleep