apiVersion: apps/v1
kind: Deployment
metadata:
  name: vweb
  labels:
    kiamol: ch09
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vweb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: vweb
        version: v3
    spec:
      containers:
        - name: web
          image: kiamol/ch09-vweb:v3
          ports:
            - name: http
              containerPort: 80

