apiVersion: v1
kind: Service
metadata:
  name: pi-web
  namespace: pi-dev
  labels:
    kiamol: ch12-lab
spec:
  ports:
    - port: 8012
      targetPort: http
  selector:
    app: pi-web
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: pi-web
  namespace: pi-test
  labels:
    kiamol: ch12-lab
spec:
  ports:
    - port: 8013
      targetPort: http
  selector:
    app: pi-web
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: pi-web
  namespace: pi-uat
  labels:
    kiamol: ch12-lab
spec:
  ports:
    - port: 8014
      targetPort: http
  selector:
    app: pi-web
  type: LoadBalancer