apiVersion: v1
kind: ConfigMap
metadata:
  name: config-network
  namespace: knative-serving
  labels:
    serving.knative.dev/release: "v0.16.0"
  annotations:
    knative.dev/example-checksum: c7f290c9
data:
  ingress.class: "contour.ingress.networking.knative.dev"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-domain
  namespace: knative-serving
data:
  kiamol.local: ""