apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    kiamol: ch08-lab
    app: nginx
spec:
  containers:
    - image: nginx:1.17-alpine
      name: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: logs
          mountPath: /var/log/nginx/
  volumes:
    - name: logs
      emptyDir: {}
