apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-web-config
  labels:
    kiamol: ch10-lab
# ConfigController.Enabled should be parameterized
data:
  config.json: |-
    {
      "ConfigController": {
        "Enabled" : false             
      }
    } 