apiVersion: v1
kind: Service
metadata:
  name: todo-web    # this needs to be templated
  labels:
    kiamol: ch10-lab
spec:
  ports:
    - port: 8081         # this should be parameterized
      targetPort: 80
  selector:              # this needs to be templated
    app: todo-web
    environment: test
  type: LoadBalancer     # this should be parameterized