apiVersion: v1
kind: Job
metadata:
  name: nginx
  labels:
    kiamol: ch08-lab
    app: nginx
spec:
  containers:
    - image: kiamol/ch03-sleep
      name: calc
      command: ['sh', '-c', 'du -h /nginx1/access.log /nginx2/access.log /nginx3/access.log']
      ports:
        - containerPort: 80
      volumeMounts:
        - name: nginx1
          mountPath: /nginx1/
        - name: nginx2
          mountPath: /nginx2/
        - name: nginx3
          mountPath: /nginx3/
  # volumes:
  # ?