apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep-2
spec:
  selector:
    matchLabels:
      app: sleep-2
  template:
    metadata:
      labels:
        app: sleep-2
    spec:
      containers:
        - name: sleep
          image: kiamol/ch03-sleep
