apiVersion: v1
kind: Service
metadata:
  name: numbers-api
spec:
  ports:
    - port: 80
  selector:
    app: lab-numbers-api
    version: v1
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: numbers-web
spec:
  ports:
    - port: 8088
      targetPort: 80
  selector:
    app: lab-numbers-web
    version: v2
  type: LoadBalancer