apiVersion: v1
kind: Service
metadata:
  name: pi-web-version
  labels:
    kiamol: ch07-lab
spec:
  ports:
    - port: 8071
      targetPort: 8080
      name: http
  selector:
    app: pi-web
  type: LoadBalancer