apiVersion: v1
kind: Service
metadata:
  name: numbers-web
  labels:
    kiamol: ch07
spec:
  ports:
    - port: 8090
      targetPort: 80
      nodePort: 30001
  selector:
    app: numbers
    component: web
  type: NodePort