apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-db-pvc
  namespace: todo
  labels:
    kiamol: ch21-lab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi