apiVersion: v1
kind: Service
metadata:
  name: numbers-api
spec:
  ports:
    - port: 80
  selector:
    app: lab-numbers-api
  type: ClusterIP
---

apiVersion: v1
kind: Service
metadata:
  name: numbers-api-external
spec:
  ports:
  - port: 8080
    targetPort: 80
  selector:
    app: lab-numbers-web-v2
  type: LoadBalancer