apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: todos.ch20.kiamol.net
  labels:
    kiamol: ch20
spec:
  group: ch20.kiamol.net
  scope: Namespaced
  names:
    plural: todos
    singular: todo
    kind: ToDo
    shortNames:
    - td
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                item:
                  type: string
                dueDate:
                  type: string
                  format: date  
      additionalPrinterColumns:
        - name: Item
          type: string
          description: What to do
          jsonPath: .spec.item
        - name: Due
          type: string
          description: When to do it
          jsonPath: .spec.dueDate