apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: kiamol-ch13-logging
  labels:
    kiamol: ch13
spec:
  selector:    
    app: elasticsearch
  ports:
  - name: elasticsearch
    port: 9200
    targetPort: 9200
  type: ClusterIP