# environment - Dev, Test or Prod
environment: Test
# whether the config UI is enabled
configControllerEnabled: false
# port for the Service:
servicePort: 8080
# type of the Service:
serviceType: LoadBalancer