apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: kiamol-ch14-lab-monitoring
spec:
  selector: 
    app: prometheus
  type: LoadBalancer  
  ports:
    - port: 9090
      targetPort: 9090
