apiVersion: v1
kind: Secret
metadata:
  name: todo-list-secret
  labels:
    kiamol: ch20
type: Opaque
stringData:
  secrets.json: |-
    {
      "ConnectionStrings": {
        "ToDoDb": "server=todo-db-mysql-master;database=todo;user=root;password=kiamol-2*2*",
        "ToDoDb-ReadOnly": "server=todo-db-mysql-replicas;database=todo;user=root;password=kiamol-2*2*"
      }
    }