apiVersion: apps/v1
kind: Deployment
metadata:
  name:  vweb
spec:
  selector:
    matchLabels:
      app: vweb
  template:
    metadata:
      labels:
        app: vweb
    spec:
      containers:
        - name: web
          image: kiamol/ch09-vweb:v1
          ports:
            - name: http
              containerPort: 80

