apiVersion: v1
kind: Service
metadata:
  name: pi-web
  namespace: kiamol-ch12-cpu
  labels:
    kiamol: ch12
spec:
  ports:
    - port: 8012
      targetPort: http
  selector:
    app: pi-web
  type: LoadBalancer