apiVersion: apps/v1
kind: Deployment
metadata:
  name: pi-web
  namespace: kiamol-ch12-cpu
  labels:
    kiamol: ch12
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pi-web
  template:
    metadata:
      labels:
        app: pi-web
    spec:
      containers:
        - image: kiamol/ch05-pi
          command: ["dotnet", "Pi.Web.dll", "-m", "web"]
          name: web
          ports:
            - containerPort: 80
              name: http
          resources:
            limits:
              cpu: 300m
