apiVersion: v1
kind: Service
metadata:
  name: buildkitd
  labels:
    kiamol: ch11
spec:
  ports:
  - port: 1234
    targetPort: buildkitd
  selector:
    app: buildkitd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: buildkitd
  labels:
    kiamol: ch11
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buildkitd
  template:
    metadata:
      labels:
        app: buildkitd
    spec:
      containers:
      - name: buildkitd
        image: moby/buildkit:v0.7.1
        args:
        - --addr
        - unix:///run/buildkit/buildkitd.sock
        - --addr
        - tcp://0.0.0.0:1234
        securityContext:
          privileged: true
        ports:
          - name: buildkitd
            containerPort: 1234