version: "3.7"

services:  
  ch11-gogs:
    image: kiamol/ch11-gogs
    build:
      context: ./gogs

  ch11-jenkins:
    image: kiamol/ch11-jenkins
    build:
      context: ./jenkins

  ch11-jenkins-current:
    image: kiamol/ch11-jenkins:2.289.3
    build:
      context: ./jenkins
      dockerfile: Dockerfile.current
