apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-proxy
  namespace: kiamol-ch14-test
spec:
  selector:
    matchLabels:
      app: todo-proxy
  template:
    metadata:
      labels:
        app: todo-proxy
      annotations:
        prometheus.io/port: "9113"
    spec:
      containers:
        - name: nginx
          image: nginx:1.17-alpine          
          ports:
            - name: http
              containerPort: 80              
          volumeMounts:
            - name: config
              mountPath: "/etc/nginx/"
              readOnly: true
        - name: exporter
          image: nginx/nginx-prometheus-exporter:0.8.0
          ports:
            - name: metrics
              containerPort: 9113
          args:
            - -nginx.scrape-uri=http://localhost/stub_status
      volumes:
        - name: config
          configMap:
            name: todo-proxy-config
              