apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-proxy
  labels:
    kiamol: ch10
spec:
  ports:
    - port: {{ .Values.servicePort }}
      targetPort: http
  selector:
    app: {{ .Release.Name }}
    component: proxy
  type: {{ .Values.serviceType }}