apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-web-secret
  labels:
    kiamol: ch12
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
stringData:
  secrets.json: |-
    {
      "ConnectionStrings": {
        "ToDoDb": "Server={{ .Release.Name }}-db;Database=todo;User Id=postgres;Password=kiamol-2*2*;"
      }
    }