apiVersion: v1
kind: Secret
metadata:
  name: todo-web-secret
  labels:
    kiamol: ch09
type: Opaque
stringData:
  secrets.json: |-
    {
      "ConnectionStrings": {
        "ToDoDb": "Server=todo-db-0.todo-db.default.svc.cluster.local;Database=todo;User Id=postgres;Password=kiamol-2*2*;",
        "ToDoDb-ReadOnly": "Server=todo-db-1.todo-db.default.svc.cluster.local;Database=todo;User Id=postgres;Password=kiamol-2*2*;"
      }
    }