apiVersion: constraints.gatekeeper.sh/v1beta1
kind: PolicyContainerProbes
metadata:
  name: container-probes
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaces:
      - "kiamol-ch16"
  parameters:
    probes: ["readinessProbe", "livenessProbe"]
    probeTypes: ["tcpSocket", "httpGet", "exec"]