apiVersion: constraints.gatekeeper.sh/v1beta1
kind: PolicyResourceLimits
metadata:
  name: resource-limits
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaces:
      - "kiamol-ch16"
