apiVersion: v1
kind: Service
metadata:
  name: pi-web
  labels:
    kiamol: ch19-lab
spec:
  ports:
    - port: 8032
      targetPort: http
  selector:
    app: pi-web-lab
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pi-web-lab
  labels:
    kiamol: ch19-lab
spec:
  selector:
    matchLabels:
      app: pi-web-lab
  replicas: 1
  template:
    metadata:
      labels:
        app: pi-web-lab    
    spec:
      containers:
        - image: kiamol/ch05-pi
          command: ["dotnet", "Pi.Web.dll", "-m", "web"]
          name: web
          ports:
            - containerPort: 80
              name: http
          resources:
            limits:
              cpu: 200m
