apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-web-config
  labels:
    kiamol: ch12
  annotations:
    "helm.sh/hook": pre-install
data:
  config.json: |-
    {
      "ConfigController": {
        "Enabled" : true
      },
      "Database" : {
        "Provider" : "Postgres"
      }
    }