apiVersion: v1
kind: Pod
metadata:
  name: sre-user
  labels:
    kiamol: ch17
spec:
  serviceAccountName: user-cert-generator
  containers:
    - name: user-cert-generator
      image: kiamol/ch17-user-cert-generator
      env:
        - name: USER_NAME
          value: sre1
        - name: GROUP
          value: sre
        - name: SET_CONTEXT
          value: "true"