apiVersion: v1
kind: Secret
metadata:
  name: petshop-connection-string-secret
  labels:
    kiamol: ch18
type: Opaque
stringData:
  connectionStrings.config: |-
    <connectionStrings>
      <add name="SQLProfileConnString" connectionString="server=petshop-db;database=MSPetShop4Profile;user id=sa;password=DockerCon!!!;min pool size=4;max pool size=4;" providerName="System.Data.SqlClient"/>
      <add name="SQLMembershipConnString" connectionString="server=petshop-db;database=MSPetShop4Services;user id=sa;password=DockerCon!!!;min pool size=4;max pool size=4;" providerName="System.Data.SqlClient"/>
      <add name="SQLConnString1" connectionString="server=petshop-db;database=MSPetShop4;user id=sa;password=DockerCon!!!;min pool size=4;max pool size=4;" providerName="System.Data.SqlClient"/>
      <add name="SQLConnString2" connectionString="server=petshop-db;database=MSPetShop4;user id=sa;password=DockerCon!!!;max pool size=4;min pool size=4;" providerName="System.Data.SqlClient"/>
      <add name="SQLConnString3" connectionString="server=petshop-db;database=MSPetShop4Orders;user id=sa;password=DockerCon!!!;min pool size=4;max pool size=4;" providerName="System.Data.SqlClient"/>
    </connectionStrings>