apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
  labels:
    kiamol: ch12
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
stringData:
  POSTGRES_PASSWORD: "kiamol-2*2*"