name: Ch02 Image Builds

on:
  push:
    paths:
      - ".github/workflows/ch02.yaml"
      - "ch02/docker-images/**"
  schedule:
    - cron: "0 2 * * 0"

jobs:
  ch02:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: ch02
        working-directory: ./ch02/docker-images
        run: |
          docker-compose build 
          docker-compose push
