name: Ch03 Image Builds

on:
  push:
    paths:
      - ".github/workflows/ch03.yaml"
      - "ch03/docker-images/**"
  schedule:
    - cron: "0 3 * * 0"

jobs:
  ch03:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: ch03
        working-directory: ./ch03/docker-images
        run: |
          docker-compose build 
          docker-compose push          

  ch03-windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@master
      - uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: ch03-windows
        working-directory: ./ch03/docker-images
        run: |          
          docker-compose -f docker-compose-windows.yml build
          docker image push kiamol/ch03-numbers-api:windows
