name: Ch12 Image Builds

on:
  push:
    paths:
      - ".github/workflows/ch12.yaml"
      - "ch12/docker-images/**"
  schedule:
    - cron: "0 12 * * 0"

jobs:
  ch12:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: ch12
        working-directory: ./ch12/docker-images
        run: |
          docker-compose build 
          docker-compose push
