name: Ch16 Image Builds

on:
  push:
    paths:
      - ".github/workflows/ch16.yaml"
      - "ch16/docker-images/**"
  schedule:
    - cron: "0 16 * * 0"

jobs:
  ch16:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: ch16
        working-directory: ./ch16/docker-images
        run: |
          docker-compose build 
          docker-compose push
