name: Ch19 Image Builds

on:
  push:
    paths:
      - ".github/workflows/ch19.yaml"
      - "ch19/docker-images/**"
  schedule:
    - cron: "0 19 * * 0"

jobs:
  ch19:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: ch19
        working-directory: ./ch19/docker-images
        run: |
          docker-compose build 
          docker-compose push
