name: Ch20 Image Builds

on:
  push:
    paths:
      - ".github/workflows/ch20.yaml"
      - "ch20/docker-images/**"
  schedule:
    - cron: "0 20 * * 0"

jobs:
  ch20:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: ch20
        working-directory: ./ch20/docker-images
        run: |
          docker-compose build 
          docker-compose push
